# https://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#_spring_cloud_gateway

server.port: 28080

spring:
  application:
      name: sc-demo-gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}-${server.port}
        port: ${server.port}
        service-name: ${spring.application.name}
    gateway:
      #locator:
      #  enabled: true
      #default-filters:
      #- AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
      # =====================================
      # 默认转发，在无法匹配其他转发时，按照此配置跳转到blueskykong.com
      - id: default_path_to_http
        uri: https://www.qq.com
        order: 10000
        predicates:
        - Path=/**
      # =====================================
      - id: service_to_demo
        uri: https://www.baidu.com
        order: 9500
        predicates:
        - Path=/user/aaa
        filters:
        - StripPrefix=1
      # =====================================
      - id: service_to_MyGatewayFilterFactory
        uri: https://github.com
        order: 9600
        predicates:
        - Path=/mygate/**
        filters:
        - StripPrefix=1
        - My0
        - My1=my1value
        - name: My2
          args:
            name: my2name
            uri: www.126.com
            uris:
            - www.baidu.com
            - www.qq.com
            - www.163.com
      # =====================================
      - id: service_to_sc-demo-consumer
        uri: lb://sc-demo-consumer
        order: 8000
        predicates:
        - Path=/**
        filters:
        - PrefixPath=/api/consumer
      # =====================================
      - id: websocket_test
        uri: ws://localhost:9000
        order: 9000
        predicates:
        - Path=/echo
      