
server: 
  port: 18080
  

spring:
  application:
    name: sc-demo-consumer
  cloud:
    consul:
      # 一般来说此处应该配置 127.0.0.1
      host: 127.0.0.1
      port: 8500
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例，默认是 0.1，数值范围  0.0 到 1.0
  zipkin:
    base-url: http://192.168.73.1:9411/ # 指定了 Zipkin 服务器的地址
  rabbitmq:
    host: 192.168.73.1
    port: 5673
    username: sc
    password: sc
      
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
    
# 默认时间是1秒超时
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 9000

ribbon:
  # 连接时间超时
  ConnectTimeout: 20
  # 读取时间超时
  ReadTimeout: 1100
  # 同一个服务实例的最大重试次数（不包括第一次调用）
  MaxAutoRetries: 1
  # 最大重试服务实例数（不包括第一个服务实例）
  MaxAutoRetriesNextServer: 1
  
# for Hystrix Metrics Stream 监控页面
# http://localhost:18080/actuator/hystrix.stream
management.endpoints.web.exposure.include: info, health, hystrix.stream